# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sea Cucumber Genome Research
subtitle: An Online Lab Notebook
email: jon.r.eilers@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  This website is about sequencing, assembling, and annotating the genome of the California Giant Sea Cucumber, also known as Apostichopus californicus. 
baseurl: "/"
url: https://joneilers.github.io/
github_username: joneilers
minimal_mistakes_skin: default
search: true

# Build settings
markdown: CommonMark
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-jupyter-notebook

author:
  name   : "Jon Eilers"
  avatar : "/assets/images/58382205_575954296244618_3014640770582839296_n.jpg"
  bio    : "Studying the genome of Apostichopus californicus"
  links:
    - label: "iNaturalist"
      icon: "fas fa-fw fa-link"
      url: "https://www.inaturalist.org/observations?place_id=any&subview=grid&user_id=jeilers"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
 
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      read_time: true
      comments: true
      share: true
      author_profile: true
      related: true
      toc_sticky: true
      sidebar:
        nav: sidebar-main
      classes: wide
      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: sidebar-main
      classes: wide
            
  # _data-cleaning
  - scope:
      path: ""
      type: data-cleaning
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: sidebar-main
      classes: wide

  # _assembly
  - scope:
      path: ""
      type: assembly
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: sidebar-main
      classes: wide

  # _annotation
  - scope:
      path: ""
      type: annotation
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: sidebar-main
      classes: wide


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
theme: minimal-mistakes-jekyll

collections:
  annotation:
    output: true
    permalink: /:collection/:path/
  assembly:
    output: true
    permalink: /:collection/:path/
  data-cleaning:
    output: true
    permalink: /:collection/:path/



  
