# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Analytical Genomics, LLC
subtitle: Studying life through lens of genomics
email: jon.eilers@analyticalgenomics.org
description: >- # this means to ignore newlines until "baseurl:"
  I am a freelance bioinformatician with expertise in genomics analysis including genome assembly, annotation, and gene expression analysis
baseurl: "/"
url: "https://analyticalgenomics.org"
github_username: joneilers
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-jupyter-notebook

author:
  name   : "Jon Eilers"
  avatar : "/assets/images/58382205_575954296244618_3014640770582839296_n.jpg"
  bio    : "Studying the genomes of *Holothuroidea* aka sea cucumbers"
  links:
    - label: "iNaturalist"
      icon: "fas fa-fw fa-link"
      url: "https://www.inaturalist.org/observations?place_id=any&subview=grid&user_id=jeilers"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joneilers"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jon.eilers@analyticalgenomics.org"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jon-eilers-a5451544"
 
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      show_date: true
      author_profile: false
      related: true
      classes: wide
      sidebar:
        nav: sidebar-main
      header:
          overlay_image: /assets/images/home/cuke1.jpg
      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      show_date: true
      toc: true
      toc_sticky: true
      layout: single
      sidebar:
        nav: sidebar-main
      header:
          overlay_image: /assets/images/home/cuke1.jpg
            
  # _data-cleaning
  - scope:
      path: ""
      type: data-cleaning
    values:
      show_date: true
      toc: true
      toc_sticky: true
      layout: single
      sidebar:
        nav: sidebar-main
      header:
          overlay_image: /assets/images/home/cuke1.jpg

  # _assembly
  - scope:
      path: ""
      type: assembly
    values:
      show_date: true
      toc: true
      toc_sticky: true
      layout: single
      sidebar:
        nav: sidebar-main
      header:
          overlay_image: /assets/images/home/cuke1.jpg

  # _annotation
  - scope:
      path: ""
      type: annotation
    values:
      show_date: true
      toc: true
      toc_sticky: true
      layout: single
      sidebar:
        nav: sidebar-main
      header:
          overlay_image: /assets/images/home/cuke1.jpg


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
collections:
  annotation:
    output: true
    permalink: /:collection/:path/
  assembly:
    output: true
    permalink: /:collection/:path/
  data-cleaning:
    output: true
    permalink: /:collection/:path/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-LYR33L3G9G"
    anonymize_ip: false # default

  
